app = "jp-protohackers"

kill_signal = "SIGINT"
kill_timeout = 30
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 10000
  protocol = "tcp"
  handlers = ["proxy_proto"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10000

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 10001
  protocol = "tcp"
  handlers = ["proxy_proto"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10001

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 10002
  protocol = "tcp"
  handlers = ["proxy_proto"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10002

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 10003
  protocol = "tcp"
  handlers = ["proxy_proto"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10003

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 10004
  protocol = "udp"

  [[services.ports]]
    port = 10004

[[services]]
  internal_port = 10005
  protocol = "tcp"
  handlers = ["proxy_proto"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10005

[[services]]
  internal_port = 10006
  protocol = "tcp"
  handlers = ["proxy_proto"]

  [services.concurrency]
    hard_limit = 500
    soft_limit = 100
    type = "connections"

  [[services.ports]]
    port = 10006

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 10007
  protocol = "tcp"
  handlers = ["proxy_proto"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10007

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 10008
  protocol = "tcp"
  handlers = ["proxy_proto"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10008

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
